I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 46, in script
    if i in inventory:
  File "game/script.rpy", line 46, in <module>
    if i in inventory:
NameError: name 'i' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 46, in script
    if i in inventory:
  File "/Users/pasaree/Downloads/renpy-8.0.3-sdk/renpy/ast.py", line 1843, in execute
    if renpy.python.py_eval(condition):
  File "/Users/pasaree/Downloads/renpy-8.0.3-sdk/renpy/python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Users/pasaree/Downloads/renpy-8.0.3-sdk/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 46, in <module>
    if i in inventory:
NameError: name 'i' is not defined

macOS-14.5-arm64-arm-64bit arm64
Ren'Py 8.3.2.24090902
vested interests test 1.0
Sun May 11 20:21:59 2025
